[graph]
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
]
all-features = true

[bans]
multiple-versions = "deny"
wildcards = "warn"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
required-git-spec = "rev"

[licenses]
allow = ["MIT", "Apache-2.0", "Unicode-3.0", "GPL-3.0"]
confidence-threshold = 1.0
